const express = require('express')
const { userRegister, userLogin, getProfile, updateProfile } = require('../controllers/user.controller')
const upload  = require('../middlewares/multer')
const { authUser } = require('../middlewares/authUser')
const userRoutes = express.Router()
userRoutes.post('/register',userRegister)
userRoutes.post('/login',userLogin)
userRoutes.get('/get-profile',authUser,getProfile)
userRoutes.post('/update-profile',upload.single('image'),authUser,updateProfile)
module.exports = userRoutes
